[Feat] NewPost View 완성
CDS-Mobile1/CDS_iOS pull request #20
Opened 2023-05-21 17:03 UTC by seongmin221

## 🌁 Background

합세 제가 맡은 View 중 NewPostVC 완성했습니다 !

## 📱 Screenshot

**[Cell drag & drop (& cell 추가 로직)]**

https://github.com/CDS-Mobile1/CDS_iOS/assets/72431640/71fd363b-32bb-4955-94d7-0292cd2e1048

<br>

<br>

**[TextField 를 이용한 내용물 작성]**

https://github.com/CDS-Mobile1/CDS_iOS/assets/72431640/4b5022db-c918-4443-a41f-13b41b471c3b

## 👩‍💻 Contents

**[Cell drag & drop (& cell 추가 로직)]**
- cell drag & drop
- cell 추가 로직 ( 제 욕심에 독단적으로 추가해서,,, 디자이너 선생님들께 말씀 드렸고 없는게 좋다고 하시면 없애려구요 ! )

<br>

**[TextField 를 이용한 내용물 작성]**
- 기존에 extension 에 빼 둔 keyboard 관련 함수를 사용했습니다 !

<br>

## ✅ Testing

제 브랜치로 오셔서 이것저것 해 보십쇼 !!
drag & drop 은 조금 길게 눌러야 적용 됩니다 !!

## 📝 Review Note

솝커톤 하고 난 뒤 이전에 짠 코드 보니까 꽤나 깔끔하게 잘 짠 것 같네요 ㅎㅎㅎ,,, 뿌듯,,,

리뷰 란에다가 간단히 코드에 대한 설명 적어둘테니까 궁금한거 있다면 언제든지 댓글 달아주십쇼 !!

## 📣 Related Issue

- close #15

## 📬 Reference

**[Cell drag & drop]**
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjprOvi8Yb_AhURBt4KHbNpAAgQwqsBegQIChAF&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DVrW_6EixIVQ&usg=AOvVaw2S-cdkzHTv3epxL2A6tNJY

2023-05-21 17:04 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Global/Extension/UIFont+.swift
그 ... 따로 이슈를 팠어야 했는데 ㅎㅎ....
지난번 PR 에서 폰트 적용이 안되어 있더라구요 ㅠㅠ 

그래서 디버깅하면서 다시 제대로 적용하기 위해 조금 뚝딱 했습니다...

2023-05-21 17:04 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
> +        static let back = UIImage.load(name: "back")
navigationBar 에 뒤로가기 버튼 입니닷 !

2023-05-21 17:05 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
> +    }
요것도 빼놓은 asset 들이 있더라구요 !

2023-05-21 17:06 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Global/UIComponent/BackButton.swift
BackButton 은 많이 쓰일 것 같아서 따로 컴포넌트로 빼두었습니다 !

2023-05-21 17:07 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
<img width="344" alt="image" src="https://github.com/CDS-Mobile1/CDS_iOS/assets/72431640/85fd93f1-193a-4196-bdf1-2ff2af6b8892">

이 버튼들에 관한 컴포넌트 입니다 !

BottomMenuContentView 는 위 4개의 버튼 중 하나를 나타내고,
NewPostBottomMenuType 으로 init 할 때 타입을 지정해주면 그에 해당하는 UI 가 구성됩니다

2023-05-21 17:07 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
> +    let menuType: NewPostBottomMenuType
요녀석 때문에 init 할 때 menuType 을 지정해두어야 합니다 !!

2023-05-21 17:08 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
> +    }
menuType 을 지정해주면 그에 따른 Property 가 생성됩니닷

2023-05-21 17:09 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
> +    private lazy var facebookToggleView = UISwitch()
얘는 왜 `lazy` 로 뒀냐 ! 하면 4 가지 메뉴 중 toggle 이 들어가는 애는 1 개이기 때문에
`private let` 으로 해서 항상 생성되게 하는 것 보다는 필요할 때에만 사용하는게 좋다고 판단했습니다 :)

2023-05-21 17:10 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
> +        }
menuType 에 따라 toggle 을 추가할지, chevron 을 추가할지 정해줍니다 !

2023-05-21 17:11 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/CollectionViewAddCellButton.swift
postImageCollectionView 의 우측에 있는 + 버튼 입니다 !
footer 로 선언해 두었습니다 !

2023-05-21 17:16 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/CollectionViewAddCellButton.swift
> +    }
+ 버튼에 action 을 추가해주는 함수입니다 !

함수로 빼 둔 이유는, 그렇지 않으면 private 을 없애야 하기 때문인데,
private 을 없앤다면 외부에서 요 CollectionViewAddCellButton 의 객체에 접근해야 하고,
그래서 은닉성(? 이 맞는지는 모르겠지만)이 침범된다고 생각했습니다

2023-05-21 17:16 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostImageCollectionViewCell.swift
postImageCollectionView 의 Cell 입니다

2023-05-21 17:17 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +        collectionView.register(CollectionViewAddCellButton.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionFooter, withReuseIdentifier: CollectionViewAddCellButton.identifier)
collectionView 에서는 footer 를 이런 식으로 register 해 줄 수 있습니다 :)

2023-05-21 17:18 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    private let bottomMenus = NewPostBottomMenuType.allCases.map { BottomMenuContentView(menuType: $0) }
BottomMenuContentView 에서 만들어 둔 NewPostBottomMenuType 을 allCases.map 을 통해
모든 버튼을 하나의 배열로 넣어준 것 입니닷

2023-05-21 17:18 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }()
위에서 만든걸 이렇게 stackView 로 관리하고자 했습니다 :)

2023-05-21 17:19 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }
이게 drag&drop 을 setting 해주는 함수입니다

`UILongPressGestureRecognizer` 라는 애를 사용해서 구현합니다 !

2023-05-21 17:22 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }
저희 @objc 를 지양하자고 했었는데,,,, 얘는 어쩔 수 없이 써야 하더라구요 ㅠ

LongPress 가 발생하면 실행될 함수 입니다 !

---
각 case 마다 실행되는게 다른데,

`.began` 은 LongPress 가 시작되었을 때, LongPress 한 cell 의 indexPath 를 가져와
내가 이 아이템을 움직이기 시작할거다 ! 라는 함수를 실행합니닷

`.changed` 은 LongPress 에 의해 무언가가 바뀌기 시작할 떄, 움직이고 있는 cell 의 위치를 업데이트 해주는 함수가 실행됩니다

`.ended` 는 Gesture 가 끝날 떄, 끝났음을 알려주는 함수가 실행됩니다

2023-05-22 00:40 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }
아직 디자이너 분들과 상의 안된 cell 추가하는 부분입니닷
디자이너분들과 이야기 해보고 넣든 빼든 할게요 ~

2023-05-22 00:42 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +        footer.configureButtonAction(to: action)
footer 를 다른 component 로 만들어 두었기 때문에 
action 추가하는걸 메소드로 접근 했습니다 !

2023-05-22 00:43 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }
textView 에는 placeholder 가 따로 없숩니다 🤔
그래서 이런 함수들로 따로 만들어주었습니다 !

2023-05-22 08:42 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    }
네~~

2023-05-22 08:45 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/CollectionViewAddCellButton.swift
> +    }
혹싀 objc 함수를 지양하는 룰 때문에 더해진 코드가 맞나요?!

2023-05-22 08:46 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
> +    private let bottomMenus = NewPostBottomMenuType.allCases.map { BottomMenuContentView(menuType: $0) }
오....map 활용 좋네요!!

2023-05-22 08:47 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
> +        }
오~ 역시 깔끔하네요 굿굿!!

2023-05-22 08:47 UTC, joonBaek12 approved these changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:47 UTC, joonBaek12 approved these changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:47 UTC, joonBaek12 approved these changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:47 UTC, joonBaek12 approved these changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:47 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 requested changes
코드 잘 봤습니다 ㅎㅎ 많이 배워갑니다~!~!

2023-05-22 08:48 UTC, joonBaek12 approved these changes

2023-05-22 14:58 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/CollectionViewAddCellButton.swift
> +    }
움 정확히 말하자면 cell 외부에서 함수에 action 을 추가하기 위해 더해진 코드입니다 !

만약 그냥 일회성으로 사용할 Button 을 사용한다면, 아래와 같이 작성할 수 있습니다 !
```swift
private let someButton: UIButton = {
    let button = UIButton()
    let action = UIAction { [weak self] _ in
        // some action
    }
    button.addAction(action, for: .touchUpInside)
    return button
}()
```

2023-05-22 16:17 UTC, sarang3009 commented
코드가 넘 깔끔하고 설명도 자세히 해줘서 좋네요 성민쟝.. 많이 배워갑니다 굿보이:)

2023-05-22 16:19 UTC, dumpwithlove approved these changes
잘봤숩니다! 최고!

2023-05-22 16:58 UTC, merged