[Feat] #125 - MainFeed Post UI 및 Tabbar UI 구현
CDS-Mobile1/CDS_iOS pull request #33
Opened 2023-05-30 08:23 UTC by sarang3009

## 🌁 Background

MainFeed 뷰 중 Post UI와 Tabbar UI 부분을 구현한 모습입니다!

## 📱 Screenshot

<img src="https://github.com/CDS-Mobile1/CDS_iOS/assets/73579035/8f4938e4-b7bb-4743-9600-69148217a425" width="400"/> 

## 👩‍💻 Contents

- Post UI 를 구현했습니다.
- Post 다중셀 적용했습니다.
- Tabbar UI 구현했습니다.
- DMlist로 이동하는 버튼 동작 연결했습니다.

## ✅ Testing

## 📝 Review Note

- Post를 하나의 TableViewCell로 만들어봤는데 그만큼 cell의 수가 적어져 파일 구조를 보기에 훨씬 편한 것 같습니다.
- 드디어 extension해서 쓰는 `UITableViewDataSource`의 역할을 이해했습니다!ㅋㅋ 다중셀 적용~.~
- 코드 중간 iOS 15.0 어쩌고가 있을텐데 그냥 평소처럼 작업하다 에러가 떠서 fix 버튼을 누르니 자동으로 생겼습니다,, 어디서 잘못된 걸까요?
- `UITabBarController` 처음 써보는데 앞으로 쓸 일이 많을 것 같은 기분! 또 새롭게 배워갑니당

## 📣 Related Issue

- close #25 

## 📬 Reference

2023-05-30 12:22 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +    private lazy var dmButton: UIButton = {
오 버튼에 레이지바 활용~~ 좋네요 ㅎㅎ

2023-05-30 12:32 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +        }
이게 뜬 이유는 deployment target ( 실사용 기기의 iOS 버전 ) 에 따라 있는 기능이 있고 없는 기능이 있기 때문입니다
예를 들어 iOS 15.0 부터 새롭게 생긴 기능은 iOS 14.0 에는 없는거죠 !

그래서 이 코드를 사용함으로써 지금 사용하고 있는 기기가 iOS 15.0 이상이 경우
if 문 내부의 내용을 사용하겠다는 거고,
iOS 15.0 보다 예전 버전이면 else 문에 들어가는 코드를 사용할거라는 뜻입니다

근데 사실 이게 왜 여기서 warning 이 뜨는지는.... 잘 모르겠네요 훔

2023-05-30 12:32 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +//            $0.horizontalEdges.bottom.equalToSuperview()
p2;
요 주석들은 없어져도 되겠죠 ?!

2023-05-30 12:33 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +        }
여기에서도 warning 이 떠서 #availiable 코드를 작성한건가요 ... ??

2023-05-30 12:35 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +@available(iOS 15.0, *)
p1;
아ㅏㅏㅏㅏ 여기에 @available 이 붙어서 위에도 #available 이 붙은 것 같네여 !!
이걸 붙인 이유가 있나요 ??
딱히 없으면 여기 포함 이 파일의 extension 에 붙은 @available 코드를 없애줘도 될 것 같습니다 ~

2023-05-30 12:36 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +    }
p3;
사실 필요는 없지만,,, postCollectionView 의 delegate = self 안해주셨어요..!!

2023-05-30 12:37 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +    }
그리고 샘플 이미지에서 봤는데 실제 인스타그램은 이미지 넘길 때 페이지 넘어가듯 하잖아요 ??
그건 postCollectionView 에 isPagingEnabled 라는 프로퍼티가 있을겁니다 !!
그거 true 로 설정해주면 될거에요 !!

2023-05-30 12:39 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +            $0.width.equalTo(375)
p1;
이건 width 를 숫자로 주면 안됩니다 ! 
현재 simulator 에서 사용하고 있는 기기가 어떤 기기인지는 모르겠으나
기기마다 width 값이 다르기 때문에, 사용하고 있는 simulator 보다 너비가 넓은 기기를 쓴다면 레이아웃이 깨질거에요 !!
고로 따로 빼 둔 SizeLiteral.Screen.Width 를 사용하는게 좋을 것 같습니다 ~ !

height 도 마찬가지로 SizeLiteral.Screen.Width 로 바꿔줘야지 정사각형이 되겠죠 ?

2023-05-30 12:40 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +            $0.top.equalToSuperview().inset(441)
p2;
top 레이아웃은 superview 의 top 에서 잡는것보다
collectionView를 기준으로 잡는게 좋지 않을까요 ??

2023-05-30 12:40 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +            $0.leading.equalToSuperview().inset(54)
p2;
요 부분도 likeButton 에 남겨둔 것과 마찬가지입니다 !

2023-05-30 12:41 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +        }
p2;
위와 동일 !!!

2023-05-30 12:41 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +
p2;
사용하지 않는 주석 삭제 ~

2023-05-30 12:42 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +            $0.leading.trailing.bottom.equalToSuperview()
이 부분은 horizontalEdges에 대해서 공부를 해보시구 취향에 맞게 사용하면 될 것 같습니다! 성민이 코드같은데.. 이번에 좋은거 하나 배워가네요!!

2023-05-30 12:43 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/TabBarViewController.swift
> +        }()
p3;
요 부분들은 viewDidLoad 안에 들어가기보단 밖에 빼는게 자연스럽지 않나... 조심스레 생각해봅니닷..

2023-05-30 12:43 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +
공백 삭제해주세여~~

2023-05-30 12:43 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/TabBarViewController.swift
> +        setViewControllers([navMainFeed, navSearch, navNewPost, navReels, navProfile], animated: false)
p2;
이런것들도 viewDidLoad 에서 촤르륵 적어두기보단 따로 함수로 빼두면 더 좋을 것 같아요 !

2023-05-30 12:46 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostCollectionViewCell.swift
> +import UIKit
전부터 궁금했던건데.. 이렇게 import를 안해도 돌아가는 경우가 있긴 하더라구요.. 혹싀 @seongmin221 성민씌는 이유를 아시는지...
이 것에 명확한 기준이 있는 것이 아니라면 혹시 모를 상황에 SnapKit import 해주세욥~

2023-05-30 12:48 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +
p1;
공백 발견 👽

2023-05-30 12:48 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostTableViewCell.swift
> +
공백 삭제해주세여~

2023-05-30 12:48 UTC, seongmin221 requested changes
고생 많으셨습니다 !!
처음 하는 부분이라 어려웠을텐데 끝까지 혼자서 해보려는 모습 대단쓰.....
리뷰 몇 가지 남겼는데 고쳐주심 감사하겠습니다 :)
하다가 또 모르겠는 부분 있으면 편하게 알려주세용 ~~

2023-05-30 12:49 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/PostTableView/PostCollectionViewCell.swift
> +import UIKit
저도 정확한 이유는 모르겠지만,,,, 잘 돌아가긴 하더라구요 .. ?
한 번만 import 해주면 되는건지 아니면 hierarchy 에 따라 안해줘도 되는건지,,,,
실험을 함 해봐야 할 것 같군요 ㅎㅎ

그래도 convention 따라서 import 해주는게 좋다고 생각합니다 ~!

2023-05-30 12:53 UTC, seongmin221 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +            $0.leading.trailing.bottom.equalToSuperview()
오호 제 코드였군여 ㅎㅋㅋㅋㅋㅋㅋㅋㅋ

오늘의 깨알 지식:

`leading`, `trailing` vs `left`, `right` 
나라마다 글자가 왼쪽에서부터 시작하는 곳이 있고, 오른쪽에서부터 시작하는 곳이 있습니다 ! 
이를 조절하기 위해, leading과 trailing 은 글자의 시작 위치도 같이 변경하고 싶을 때 사용하구요,
글자의 시작 위치는 굳이 설정해줄 필요가 없다 ! 면 left, right 를 써도 됩니다 ~

그리고 horizontalEdges 는 left 와 right 를 모두 포함하는 것이고,
horizontalDirectionalEdges (directionalHorizontalEdges 인가 ?) 는 leading과 trailing 을 포함해서 말하는 거랍니다 ~

2023-05-30 13:13 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
> +            $0.leading.trailing.bottom.equalToSuperview()
오.. 전 그냥 혹시 모를 상황에 대비해서 그냥 leading으로 통일해서 썼는데.. 역시 섬세한남자....

SnapKit에는 정말 다양한 속성들이 있군요..! 성민쌤...많이 배워갑니다 ㅎㅎㅎ

2023-05-30 13:18 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/TabBarViewController.swift
> +        }()
p2;
보통 외부에서 접근 할 필요가 없는 Property들 같은 경우에는 viewDidLoad 밖에 선언해줍니다! 
외부에서 접근이 필요한 객체가 아니라면 Life Cycle 밖에 선언해주어 가독성을 높일 수 있어요~

2023-05-30 13:19 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/TabBarViewController.swift
> +
p2;
공백 삭제해주세여~

2023-05-30 13:19 UTC, joonBaek12 commented on Instagram-iOS/Instagram-iOS/Screens/MainFeed/TabBarViewController.swift
> +
p2;
공백 삭제해주세여~

2023-06-01 16:07 UTC, joonBaek12 approved these changes
고생했어요~!~!

2023-06-01 22:37 UTC, seongmin221 approved these changes
좋습니다 !!

추가로 하나만 말씀 드리자면 리뷰 남겨둔거에 커밋 링크를 남겨두시면 저희가 확인하기 더 편하답니다 :)
무슨 소린지 모르겠다면 물어봐주세요 ~

2023-06-02 11:33 UTC, merged